; Author : Robert Sander

.include <m328pdef.inc>

.ORG 0		
.SET	A = 28
.SET	B = 4
	
	LDI R16, A		;LOAD IN A 'TOP NUMBER' MULTIPLIER
	LDI R17, B		;LOAD IN B 'BOTTOM NUMBER' MULTIPLICAND
	LDI R18, 0		;RESULT REGISTER
L1:
	ADD R18, R16	;ADD THE MULTIPLIER TO THE RESULT REGISTER
	DEC R17			;
	CPI R17, 0		;CHECK TO SEE IF MULTIPLICAND HAS FINISHED ALL BITS
	BRNE L1			;IF THE MULTIPLICAND STILL HAS VALUES TO MULTIPLY THEN LOOP TO L1:

END: RJMP END		;FINISHED AND THE DESIRED RESULT SHOULD BE IN R18