; Author : Robert Sander

.include <m328pdef.inc>

.ORG 0		
.SET	A = 15
.SET	B = 17
	
	LDI R16, A			;LOAD IN A 'TOP NUMBER' MULTIPLIER
	LDI R17, B			;LOAD IN B 'BOTTOM NUMBER' MULTIPLICAND
	LDI R18, 0			;RESULT REGISTER
	
L1:
	LSL R18	;SHIFT RESULT REGISTER LEFT EVERY LOOP 
	LSR R17	;SHIFT MULTIPLIER RIGHT TO CHECK IF LSB IS 0 OR 1
	BRCC DONTADD	;IF 1 CONTINUE AND ADD THE MULTIPLIER TO THE RESULT REGISTER, IF CARRY IS CLEAR GO TO DONADD:
	ADD R18, R16	;ADD THE MULTIPLIER TO THE RESULT REGISTER
	CPI R17, 0		;CHECK TO SEE IF MULTIPLICAND HAS FINISHED ALL BITS
	BRNE L1			;IF THE MULTIPLICAND STILL HAS VALUES TO MULTIPLY THEN LOOP TO L1:
DONTADD:			
	CPI R17, 0		;CHECK TO SEE IF MULTIPLICAND HAS FINISHED ALL BITS
	BRNE L1			;IF THE MULTIPLICAND STILL HAS VALUES TO MULTIPLY THEN LOOP TO L1:
END: rjmp END		;FINISHED AND THE DESIRED RESULT SHOULD BE IN R18