; Author : Robert Sander

.include <m328pdef.inc>

.ORG 0		
	
	LDI R18, 0						;RESULT REGISTER 1
	LDI R19, 0						;RESULT REGISTER 2
	LDI R20, 0						;RESULT REGISTER 3
	LDI R22, 2						;LOAD IN MULTIPLICAND_8	'BOTTOM NUMBER'
	LDI R24, MULTIPLICAND_16_LOW	;LOAD IN MULTIPLICAND_16_LOW 'TOP NUMBER'
	LDI R25, MULTIPLICAND_16_HIGH	;LOAD IN MULTIPLICAND_16_HIGH 'TOP NUMBER' 
	
L1:
	LSL R18			;SHIFT RESULT REGISTER LEFT EVERY LOOP 
	LSL R19			;SHIFT RESULT REGISTER LEFT EVERY LOOP 
	LSL R20			;SHIFT RESULT REGISTER LEFT EVERY LOOP 
	LSR R22			;SHIFT MULTIPLICAND_8 RIGHT TO CHECK IF LSB IS 0 OR 1
	BRCC DONTADD	;IF 1 CONTINUE AND ADD THE MULTIPLIER TO THE RESULT REGISTER, IF CARRY IS CLEAR GO TO DONADD:
	ADD R18, R16	;ADD THE MULTIPLIER TO THE RESULT REGISTER
	CPI R17, 0		;CHECK TO SEE IF MULTIPLICAND HAS FINISHED ALL BITS
	BRNE L1			;IF THE MULTIPLICAND STILL HAS VALUES TO MULTIPLY THEN LOOP TO L1:
DONTADD:			
	CPI R17, 0		;CHECK TO SEE IF MULTIPLICAND HAS FINISHED ALL BITS
	BRNE L1			;IF THE MULTIPLICAND STILL HAS VALUES TO MULTIPLY THEN LOOP TO L1:
END: rjmp END		;FINISHED AND THE DESIRED RESULT SHOULD BE IN R18
	
	;LDI R18, RESULT_1
	;LDI R19, RESULT_2
	;LDI R20, RESULT_3
	;LDI R22, MULTIPLICAND_8
	;LDI R24, MULTIPLICAND_16_HIGH
	;LDI R25, MULTIPLICAND_16_LOW
	
	;test the multiplicand LSB if 0 dont add, shift multiplicand in the results
	;if 1 add multiplier to result, check for carry, loop