; Author : Robert Sander

.include <m328pdef.inc>

.ORG 0		
.SET	A = 64
.SET	B = 24
	
	LDI R16, A		;LOAD IN A 'TOP NUMBER' MULTIPLIER
	LDI R17, B		;LOAD IN B 'BOTTOM NUMBER' MULTIPLICAND
	
	LDI R19, 0		;RESULT REGISTER
	LDI R20, 0		;2ND RESULT REGISTER
L1:
	CPI R17, 0
	BREQ L2
	DEC R17
	ADD R19, R16	;ADD THE MULTIPLIER TO THE RESULT REGISTER
	BRCC NOCARRY
	INC R20
NOCARRY:
	CPI R17, 0		;CHECK TO SEE IF MULTIPLICAND HAS FINISHED ALL BITS
L2:	BRNE L1			;IF THE MULTIPLICAND STILL HAS VALUES TO MULTIPLY THEN LOOP TO L1:

END: RJMP END		;FINISHED AND THE DESIRED RESULT SHOULD BE IN R18



	;LDI R18, RESULT_1
	;LDI R19, RESULT_2
	;LDI R20, RESULT_3
	;LDI R22, MULTIPLICAND_8
	;LDI R24, MULTIPLICAND_16_HIGH
	;LDI R25, MULTIPLICAND_16_LOW