; Author : Robert Sander

.include <m328pdef.inc>

.ORG 0				;BEGIN AT THIS LOCATION
	
	LDI R22, 255	;LOAD IN MULTIPLICAND_8 'BOTTOM NUMBER'
	LDI R24, 255	;LOAD IN MULTIPLICAND_16_LOW 'TOP 'RIGHT PART' NUMBER'
	LDI R25, 0xFF	;LOAD IN MULTIPLICAND_16_HIGH 'TOP 'LEFT PART' NUMBER'
	LDI R26, 0		;LOAD ZERO INTO REGISTER R26
	
	CPI R22, 0		;IF MULTIPLIER EQUALS 0
	BREQ DONE		;IF MULTIPLIER EQUALS 0 GO TO DONE:
L1:
	ADC R18, R24	;ADD WITH CARRY THE VALUE OF R24 AND R18 AND STORE THE RESULT IN R18
	ADC R19, R25	;ADD WITH CARRY THE VALUE OF R25 AND R19 AND STORE THE RESULT IN R19
	ADC R20, R26	;ADD WITH CARRY THE VALUE OF R26 AND R20 AND STORE THE RESULT IN R20
	DEC R22			;DECREMENT R22, ITERATIVE ADDITION FOR MULTIPLICATION
	CPI R22, 0		;CHECK TO SEE IF REGISTER R22 IS ZERO
	BRNE L1			;IF REGISTER R22 DOES NOT EQUAL ZERO GO TO L1: OTHERWISE CONTINUE
DONE:				;GO HERE IF THE MULTIPLIER EQUALS ZERO
END: RJMP END		;FINISHED AND THE DESIRED RESULT SHOULD BE IN R18
